Feature/replace_makefile_with_msbuild
5minds/Template.ProcessCube.Project pull request #22
Opened 2023-03-31 09:41 UTC by SeeSharpProgrammer

## Changes

- Add Build targets to replace Makefile
- Update Readme.md Files
- Add **/frontend/build/ to .gitignore

## Tasks

[factro](https://cloud.factro.com/5681c8b0/?p=task&pi=d1d49ee7-216d-4cec-ab50-7287a344614d)

PR: #22

2023-03-31 15:43 UTC, Jeremy-Hill-02 commented
Ich kann nicht auf die factro Task zugreifen @DevBastiS (oder der Link ist korrupt)

2023-04-02 15:18 UTC, Jeremy-Hill-02 requested changes
Ich empfehle `markdownlint` als Markdown linter.

Die Makefile zu den UI-Tests wird noch nicht ersetzt.

Die Makefiles können mit diesem PR natürlich gelöscht werden.

Vor dem Merge nicht vergessen die Version hochzuziehen!

2023-04-02 15:18 UTC, gazer42 commented on Makefile
> +	dotnet new install artifacts/*.nupkg
Funktioniert nicht mit .NET 6, deswegen würde ich das reverten

2023-04-02 15:18 UTC, gazer42 commented on Makefile
> +	cd ~ && dotnet new uninstall Template.ProcessCube.Project || echo "No template uninstalled because there was no template"
wie oben

2023-04-02 15:18 UTC, gazer42 commented on README.md
> +    dotnet build /t:Install-Template
heißt das es wird erst `dotnet build` und dann `msbuild -t:Install-Template` ausgeführt?

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.props
> +</Project>
```suggestion
</Project>

```

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.props
> +        <DockerImageName>$(MSBuildProjectName.ToLower())</DockerImageName>
Außerdem werden Punkte mit Unterstrichen ersetzt

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +</Project>
```suggestion
</Project>

```

2023-04-02 15:18 UTC, gazer42 commented on TemplateHandler.csproj
> +    <Exec Command="dotnet new install $(LocalNuget)/*.nupkg"  ConsoleToMSBuild="true" />
```suggestion
    <Exec Command="dotnet new --uninstall Template.ProcessCube.Project" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="Install-Template">
    <CallTarget Targets="Template" />
    <CallTarget Targets="Uninstall-Template" />
    <Exec Command="dotnet new --install $(LocalNuget)/*.nupkg"  ConsoleToMSBuild="true" />
```

wie oben begründet

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +    <Message Importance="High" Text="taking docker down:" />
```suggestion
  <Target Name="DockerComposeDown">
    <Message Importance="High" Text="docker compose down:" />
```

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +    <Exec Command="docker compose rm -f app" WorkingDirectory="$(DockerRoot)"
Könnte man dann in ein eigenes Target tun wie `RemoveAppDockerImage` und hier aufrufen.
Edit: Der Task `RemoveDockerImage` sollte das doch schon machen oder?

2023-04-02 15:18 UTC, gazer42 commented on TemplateHandler.csproj
> +  <Target Name="Install-Template">
```suggestion
  <Target Name="Template">
    <Message Importance="High" Text="Create Template in $(LocalNuget):" />
    <RemoveDir Directories="$(LocalNuget)" />
    <Exec Command="dotnet pack -o $(LocalNuget)"  ConsoleToMSBuild="true" />
  </Target>
  <Target Name="UninstallTemplate">
    <Exec Command="dotnet new uninstall Template.ProcessCube.Project" ConsoleToMSBuild="true" />
  </Target>
  <Target Name="InstallTemplate">
```
Sonst hattest du ja auch keine Bindestriche benutzt

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +  <Target Name="Clear">
```suggestion
  <Target Name="Clean">
```

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +  <Target Name="NpmClear">
```suggestion
  <Target Name="NpmClean">
```

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +  </Target>
```suggestion
```

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/README.md
> +Nach dem Erzeugen eines neuen Templates, kann dieses Bearbeitet werden
```suggestion

```

2023-04-02 15:18 UTC, gazer42 commented on Template.ProcessCube.Project/README.md
> +oder im Docker Desktop Programm über das Stop-Symbol
```suggestion
```

Das weiß man i.d.R., wenn man schon mal Docker gemacht hat (was als Voraussetzung angegeben ist). Nichts Projektspezifisches, kann also raus

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +aufgerufen.
```suggestion

Folgender Befehl:
 - Räumt die Docker-Container ab
 - Löscht das Docker-Image der App
 - Löscht die `node_modules` und die `package-lock.json` im Frontend
 - Löscht die Datenbank der 5Minds Engine
 
```zsh
dotnet build /t:Clean
\```
```

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +  <Target Name="DockerBuild">
Name ist ein wenig irreführend, weil ja nicht bloß Docker Dinge gebaut werden

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +dotnet build /t:Clear
Warum sollte man eigentlich vor dem Clean bauen wollen? `msbuild -t:Clean`

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +Dieser Abschnitt zeigt die Grundlegenden Befehle, die zum Starten des Projekts notwendig sind:
```suggestion

Dieser Abschnitt zeigt die Grundlegenden Befehle, die zum Starten des Projekts notwendig sind.
```

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +dotnet build /t:Start
```suggestion
dotnet build /t:Run
```
Hieß vorher auch `make run`.
Würde diesen Befehl auch nach oben packen, weil das quasi der "All-in-One" Befehl und damit der interessanteste ist.

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +
```suggestion
Folgender Befehl:
 - Installiert die NPM-Pakete
 - Baut das Frontend
 - Baut/pulled die benötigten Docker-Images
 
```zsh
dotnet build /t:Setup
\```

Dadurch wird die Anwendung auf den Start vorbereitet.
```

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +```
Du kannst auf mehrere Projekte auf einmal bauen, sofern sie der Solution hinzugefügt wurden. Da in den angegebenen Befehlen aber sowieso vorher ein `dotnet build` ausgeführt wird, ist der Punkt eh mehr oder minder obsolet

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +```
```suggestion
```

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +### Docker erzeugen
```suggestion
### Build
```

2023-04-02 15:18 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +### Projekt/Docker starten
```suggestion
### Start
```

2023-04-11 07:23 UTC, SeeSharpDeveloper commented on Template.ProcessCube.Project/README.md
> +```
Das Problem bei mehreren Projekten in der Solution ist, dass bei allen Projekten dann auch die gleichen Targets vorhanden sein müssen. Ansonsten versucht der Build ein nicht vorhandenes Target zu bauen und wirft einen Fehler.

2023-04-11 07:38 UTC, SeeSharpDeveloper commented on Template.ProcessCube.Project/README.md
> +dotnet build /t:Start
es gibt ein eigenes MsBuild Build Target namens Run, daher ist dieses in Konflikt mit dem selbst erstellten Run. Daher habe ich Start eingeführt. Bin offen für andere Vorschläge, sollte nur kein BuildTarget Name von https://learn.microsoft.com/de-de/visualstudio/msbuild/msbuild-targets?view=vs-2022 sein

2023-04-11 07:46 UTC, SeeSharpProgrammer commented on Template.ProcessCube.Project/README.md
> +dotnet build /t:Clear
Wenn ich das richtig sehe, muss der normale MSbuild noch eingebaut werden. Also entweder erst ganz normal dotnet build aufrufen und danach das Target, oder im setup Target das Projekt builden.
Das kann ich aber heute noch einmal testen.

2023-04-11 07:51 UTC, SeeSharpProgrammer commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +  <Target Name="Clear">
Clean ist ein vorgegebenes Build Target und sollte nicht überschrieben werden.

2023-04-11 08:05 UTC, SeeSharpProgrammer commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Template.ProcessCube.Project.targets
> +  <Target Name="DockerBuild">
Hast Recht, Vorschläge:
- ProcessCubeBuild
- ProcessBuild
- BuildNodeAndDocker
- BuildApp

2023-04-11 08:07 UTC, SeeSharpProgrammer commented on README.md
> +    dotnet build /t:Install-Template
nein, es wird nur das Target ausgeführt. Man muss vorher einmal dotnet build machen. Oder das einen Buildvorgang anstoßen.

2023-04-12 05:38 UTC, closed without merging

2023-04-12 07:08 UTC, Jeremy-Hill-02 commented on README.md
> +    dotnet build /t:Install-Template
Wenn durch `dotnet build /t:Install-Template` kein Build ausgeführt wird, würde ich lieber die `msbuild -t:Install-Template` Syntax verwenden. Da ist klarer, dass nur das Target ausgeführt wird

2023-04-12 07:09 UTC, Jeremy-Hill-02 commented on Template.ProcessCube.Project/README.md
> +dotnet build /t:Start
Achso, dann würde ich es bei Start belassen