Update Versions
5minds/Template.ProcessCube.Project pull request #31
Opened 2024-06-10 13:05 UTC by luisthieme

## Changes

1. dotnet dependecies wurden geupdated

2024-06-11 09:19 UTC, gazer42 requested changes

2024-06-11 09:19 UTC, gazer42 commented on README.md
> -    ```
Was hat das mit dem Updaten der Dependencies zu tun?

Außerdem verstehe ich nicht, warum es gelöscht werden sollte.

2024-06-11 09:19 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Worker/Example/ExampleHandler.cs
> +
Diese Änderung erschließt sich mir nicht.

2024-06-11 09:19 UTC, gazer42 commented on Template.ProcessCube.Project/README.md
> -Daraufhin wird der Docker Container zusammengebaut und gestartet.
Wird kein msbuild mehr genutzt?

2024-06-11 09:19 UTC, gazer42 commented on Template.ProcessCube.Project/README.md
> +Das builden funktioniert mit dem Befehl `docker compose build`.
```suggestion
Das Builden funktioniert mit dem Befehl `docker compose build`.
```

2024-06-11 09:20 UTC, gazer42 requested changes, later dismissed

2024-06-11 09:20 UTC, gazer42 commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/Worker/Example/ExampleHandler.cs
> +using Template.ProcessCube.Project.Worker.Example;
Diese Änderung erschließt sich mir nicht

2024-06-13 06:29 UTC, ElRaptorus reviewed
Die Engine Config in der Dockerfile ist auch stark veraltet. 
https://github.com/5minds/Template.ProcessCube.Project/blob/develop/Template.ProcessCube.Project/docker-compose.yml#L4-L9

Die aktuellste Engine Version ist 17.0.1.
Und die Volume Namen könnten auch ein Update vertragen. Seit v16 sind die im Engine Image wie folgt konfiguriert::
- `/config` für die Konfiguration
- `/database` als Ablage für die SQLite DB

Siehe auch: https://github.com/5minds/ProcessCube.Engine/blob/develop/Dockerfile#L34-L38 

Zumindest sollte wohl das "AtlasEngineFullstackServer" besser verschwinden.

2024-06-13 06:29 UTC, ElRaptorus commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/frontend/package.json
>      "@atlas-engine/atlas_engine_client": "^4.2.5",
Die Pakete müssen auch ausgetauscht werden.

2024-06-19 07:05 UTC, SebastianWehmeyer commented on Template.ProcessCube.Project/README.md
> -Daraufhin wird der Docker Container zusammengebaut und gestartet.
Luis hat mir den PR übergeben und meinte msbuild wird nicht mehr genutzt

2024-07-16 14:13 UTC, ElRaptorus approved these changes

2024-07-16 14:13 UTC, ElRaptorus commented on Template.ProcessCube.Project/apps/Template.ProcessCube.Project/frontend/package.json
> +    "@5minds/processcube_engine_client": "^4.2.5",
```suggestion
    "@5minds/processcube_engine_client": "^5.0.0",

```

2024-08-09 12:28 UTC, merged